### ISSUE TITLE
[FEATURE] Sort screenshots into language/region-based folders

### ISSUE THREAD

**Issue by Blackjacx** [ChargePoint/xcparse#34]
Now with the new Testplans we are able to generate one result bundle that includes multiple languages. 

It would be nice to be able to have a language based sorting mechanism similar to `device` and `os`.

**Comment by Blackjacx** [comment]
Oh forget about that! It is already covered by the option `--test-run` which separates by the TestPlan configuration name 👍 (maybe an impractical parameter name ;-))

**Comment by abotkin-cpi** [comment]
Reopening as it may be worthwhile to consider having this separate from test plan configurations since that only support Xcode 11 xcresults forward & I could imagine some folks may want to group screenshots by language & region of the Simulator across test plan configurations due to Dark Mode screenshots or other scenarios where the test plan configuration enables a certain feature in the app for a screenshot capture.

@Blackjacx On the ```--test-run``` flag, yeah it's probably not the best name.  Any ideas of a name that may work better?  ```--test-plan``` or```test-plan-config``` might work but curious what others would've expected.

**Comment by Blackjacx** [comment]
`--test-plan-config` is long but sweet. That ails it :)

**Comment by abotkin-cpi** [comment]
This is now resolved in xcparse 2.1.0.  xcparse 2.1.0 introduces new ```--language``` and ```--region``` flags that can be used to divide screenshots & attachments by the test language and/or test region.  Best usage is when you want to group across test plan configurations & so if you only have one configuration per language/region, it may not be preferable to ```--test-plan-config```.  ```-test-run``` is now marked as deprecated and the naming ```--test-plan-config``` is available starting in this release too.

To upgrade xcparse, run:

```
brew upgrade xcparse
```

Thanks for your feature suggestion & feedback, @Blackjacx!
